apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: monitoring-pod
    component: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 3030

