apiVersion: v1
kind: Pod
metadata:
  name: apache-pod-2
spec:
  containers:
  - name: apache-container-2
    image: alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /var/www/html
      name: html-volume
  volumes:
  - name: html-volume
    hostPath:
      path: /home/$(whoami)/container/web

